# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ios general' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ios general
  pod 'HSDatePickerViewController', '~> 1.0'

  target 'ios generalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios generalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
